#!/bin/bash
clear
# load popular docker images of nearly all LLM/AI images available
echo -e "loading [ai/deepseek-r1-distill-llama]"
echo -e "\t`docker model pull ai/deepseek-r1-distill-llama:70B-Q4_0`"
echo -e "loading [ai/deepcoder-preview]"
echo -e "\t`docker model pull ai/deepcoder-preview`"
echo -e "loading [ai/gemma3:4B-Q4_0]"
echo -e "\t`docker model pull ai/gemma3:4B-Q4_0`"
echo -e "loading [ai/gemma3n:2B-F16]"
echo -e "\t`docker model pull ai/gemma3n:2B-F16`"
echo -e "loading [ai/llama3.1:8B-F16]"
echo -e "\t`docker model pull ai/llama3.1:8B-F16`"
echo -e "loading [ai/llama3.2:3B-Q4_0]"
echo -e "\t`docker model pull ai/llama3.2:3B-Q4_0`"
echo -e "loading [ai/llama3.3:3B-Q4_0]"
echo -e "\t`docker model pull ai/llama3.3:70B-Q4_0`"
echo -e "loading [ai/mistral-nemo]"
echo -e "\t`docker model pull ai/mistral-nemo`"
echo -e "loading [ai/qwen2.5]"
echo -e "\t`docker model pull ai/qwen2.5:7B-Q4_0`"
echo -e "loading [ai/qwen3]"
echo -e "\t`docker model pull ai/qwen3:14B-Q6_K`"
echo -e "loading [ai/qwq]"
echo -r "\t`docker model pull ai/qwq:32B-Q4_0`"

